image: node:latest

services:
    - mysql:latest

cache:
    paths:
        - node_modules/

stages:
    - build
    - test
    - deploy

build_job:
    stage: build
    script:
        - npm install
        - echo "Build"

test_job:
    stage: test
    script:
        - npm test
        - node ./specs/start.js ./specs/async.spec.js
        - echo "Testing"

deploy_job:
    stage: deploy
    script:
        - echo "Deploying"
        - echo "Application Successfully Deployed!"
    environment: production
