image: node:18.17.0

#services:
#    - mysql:latest

cache:
    paths:
        - src/frontend/node_modules/
        - src/backend/node_modules/

stages:
    - build
    - test
    - deploy

build-job:
    stage: build
    script:
        - npm install
        - echo "Compiling the code..."
        - echo "Compile complete."

unit-test-job: 
    stage: test 
    script:
        - npm test
        - echo "Running unit tests... This will take about 15 seconds."
        - sleep 15
        - echo "Code coverage is 90%"

deploy-job:    
    stage: deploy
    environment: production
    script:
        - echo "Deploying application..."
        - echo "Application successfully deployed."
