image: node:18.17.0

stages:
  - test
  - deploy

before_script:
  - echo "Compiling the code..."
  - echo "Compile complete."

unit-test-backend-job:
  stage: test
  script:
    - echo "Running unit tests for backend... This will take about 60 seconds."
    - cd ./src/backend
    - npm install
    - npm test
    - sleep 60
    - echo "Code coverage is 90%"
  variables:
    EXAMPLE: $EXAMPLE

unit-test-frontend-job:
  stage: test
  script:
    - echo "Running unit tests for frontend... This will take about 60 seconds."
    - cd ./src/frontend
    - npm install
    - npm test
    - sleep 60
    - echo "Code coverage is 90%"

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
